# ==========================================
#           mCore AYARLAR DOSYASI
# ==========================================

prefix: "<bold><gradient:#29f057:#41f06a>mCore</gradient></bold> <dark_gray>»</dark_gray> "

# Actionbar
actionbar:
  enabled: true
  interval: 30
  message: "<green>ᴍᴀꜱᴋᴇᴘʀᴀᴄ.ᴏʀɢ"
  disabled-worlds:
    - "world"

# Combat Log
combat-log:
  enabled: true
  duration: 15
  kill-on-quit: true
  whitelisted-worlds:
    - "world"
    - "world_nether"
    - "world_the_end"
    - "orman"

# ÖLÜM KOMUTLARI (YENİ)
# Oyuncu belirli bir dünyada ölünce konsol tarafından komut çalıştırılır.
death-commands:
  enabled: true
  worlds:
    # Dünya Adı:
    #   - "komut"
    world:
      - "eco take %player% 100"
      - "msg %player% <red>Öldüğün için paranızdan kesinti yapıldı."
    orman:
      - "msg %player% <yellow>Ormanda öldün!"

# Kill Efektleri
kill-system:
  enabled: true
  prevent-self-kill-title: true
  sound: "BLOCK_ENCHANTMENT_TABLE_USE"
  title:
    enabled: true
    main: ""
    sub: "<green><bold>+1 ᴋɪʟʟ</bold></green>"

# TPA Ayarları
tpa:
  timeout: 60
  delay: 3
  countdown-sound: "BLOCK_NOTE_BLOCK_HAT"
  sound-on-request: "BLOCK_NOTE_BLOCK_PLING"
  sound-on-teleport: "ENTITY_ENDERMAN_TELEPORT"
  # Etkinlik süresi (Saniye)
  event-duration: 120

# World Change
world-change:
  enabled: true
  commands:
    spawn: "kit1"

# RTP Queue (1v1 Sıra)
rtp-queue:
  world: "sand"
  min-range: 100
  max-range: 2000
  distance-between-players: 8
  waiting-sound: "MUSIC_DISC_MELLOHI"
  timeout-seconds: 96
  timeout-sound: "ENTITY_VILLAGER_NO"
  match-sound: "ENTITY_PLAYER_LEVELUP"
  command: "kit1"

# RTP Duel (İstekli Düello) (GÜNCELLENDİ)
rtp-duel:
  world: "sand"          # Düello dünyası
  min-range: 500         # Koordinat aralığı
  max-range: 5000
  distance-between-players: 10
  command: "kit1"